// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BlazingPizza.Server.Models
{
    [DbContext(typeof(PizzaStoreContext))]
    public partial class PizzaStoreContextModel : RuntimeModel
    {
        static PizzaStoreContextModel()
        {
            var model = new PizzaStoreContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PizzaStoreContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
